# Generated by Django 4.1.6 on 2023-07-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='home1',
        ),
    ]
